### ISSUE TITLE
Connecting to RDS: Connection unexpectedly destroyed

### ISSUE THREAD

**Issue by CanTheAlmighty** [malthe/ts-postgres#59]
I've been trying to connect to my RDS instance for a while, an instance I frequently login via Postico (an app), prisma and sequelize, all without issue. I tried this library to do some simple copy and moving around with little baggage, but as soon as I moved from localhost to the RDS instance I get the error

```/Users/can/Work/sandbox-pooling/node_modules/ts-postgres/dist/src/client.js:239
            throw new Error('Connection unexpectedly destroyed');
            ^

Error: Connection unexpectedly destroyed
    at Client.end (/Users/can/Work/sandbox-pooling/node_modules/ts-postgres/dist/src/client.js:239:19)
    at abort (/Users/can/Work/sandbox-pooling/node_modules/ts-postgres/dist/src/client.js:99:22)
    at TLSSocket.<anonymous> (/Users/can/Work/sandbox-pooling/node_modules/ts-postgres/dist/src/client.js:148:21)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)```

I created a new project and I still get the same issue

```typescript
    const client = new Client({
        database: 'somedb',
        host: 'foobar.D34DB33F.rds.us-east-1.rds.amazonaws.com',
        port: 5432,
        user: 'auser',
        password: 'averygoodpassword',
    })

    await client.connect()

    const res = await client.query('SELECT * FROM entity.user LIMIT 1')
    console.log(res.rows)
```

Only happens with RDS, I tried passing the RDS Certificate Authority ([rds-ca-2019.pem](https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-download-ssl-certificate-for-managed-database)), and nada, still the same issue.

**Comment by jimmiebtlr** [comment]
I'm having the same issue on google cloud sql, running ts-postgres on vercel functions.

**Comment by jimmiebtlr** [comment]
I was able to get another log when running locally, this was related to SSL.

```
- error unhandledRejection: Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1558:34)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket._finishInit (node:_tls_wrap:977:8)
    at ssl.onhandshakedone (node:_tls_wrap:771:12) {
  digest: undefined
}
- error uncaughtException: Error: Connection unexpectedly destroyed
    at Client.end (/workspaces/sites/src/apps/toDone/node_modules/ts-postgres/dist/src/client.js:239:19)
    at abort (/workspaces/sites/src/apps/toDone/node_modules/ts-postgres/dist/src/client.js:99:22)
    at TLSSocket.<anonymous> (/workspaces/sites/src/apps/toDone/node_modules/ts-postgres/dist/src/client.js:148:21)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  digest: undefined
}
```

**Comment by malthe** [comment]
I wonder if setting the environment variable `PGSSLMODE` (or configuration option) to `verify-ca` or `require` makes a difference.

**Comment by malthe** [comment]
Best guess here is that something's wrong with the root certificates in your system. See also the `NODE_EXTRA_CA_CERTS` option.
