### ISSUE TITLE
Error: Queue is Empty

### ISSUE THREAD

**Issue by camfeghali** [malthe/ts-postgres#61]
I'm running tests using jest, [jest-postgres,](https://github.com/shelfio/jest-postgres) to spin up a local postgres instance. and using ts-postgres to access that postgres instance. 

Tests are failing with the following error:

```
    Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "ts-postgres: Error: Queue is empty".

      at console.warn (../../../node_modules/@jest/console/build/BufferedConsole.js:191:10)
      at log (../../../node_modules/ts-postgres/src/logging.ts:7:16)
      at Object.warn (../../../node_modules/ts-postgres/src/logging.ts:19:13)
      at Socket.<anonymous> (../../../node_modules/ts-postgres/src/client.ts:386:24)
```

This is the code that executes when making queries:

```
  async function connection() {
    if (!client || client.closed) {
      client = new Client(config);
      await client.connect();
      return client;
    }
    return client;
  }
  async function query<T>(query: string): Promise<T[]> {
    try {
      const conn = await connection();
      const queryResult = await conn.query(query);
      const { rows, names } = queryResult;
      return rows.map((row) => mapToObj<T>(row, names));
    }
  }
```
Am I missing something?

**Comment by malthe** [comment]
Can you try to do `await pgClient.connect()` first – just to see if it's failing during the initial connection?

**Comment by camfeghali** [comment]
hey @malthe , thanks for getting back to me. Maybe I should've shared this from the start. 

I created a small wrapper around `ts-postgres` like so:
```
export default function postgresClient(config: PostgresConfig) {
  let client: Client | undefined;

  const { schema, tableName } = config;

  async function connection() {
    if (!client || client.closed) {
      client = new Client({ ...config, keepAlive: false });
      await client.connect();
      return client;
    }
    return client;
  }
  async function query<T>(query: string): Promise<T[]> {
    const conn = await connection();
    try {
      const queryResult = await conn.query(query);
      const { rows, names } = queryResult;
      return rows.map((row) => mapToObj<T>(row, names));
    } 
  }

  return { query };
```

With which I then run:
```
export async function get(props) {
    const { schema, tableName } = DB_CONFIG;
    const whereClause = buildWhereClause(props);
    const query = `SELECT * from ${schema}.${tableName} ${whereClause};`;
    const pgClient = postgresClient(DB_CONFIG);

    return await pgClient.query<RecommendableProduct>(query);
}
```
Are you suggesting I return a promise which resolves to `  return { query };`

**Comment by malthe** [comment]
What does a `try { }` block without catch/finally do?

**Comment by camfeghali** [comment]
nothing, I omitted the catch/finally to avoid clutter. It's actually this:

```
  async function query<T>(query: string): Promise<T[]> {
    const conn = await connection();
    try {
      const queryResult = await conn.query(query);
      const { rows, names } = queryResult;
      return rows.map((row) => mapToObj<T>(row, names));
    } catch (error) {
      if (error instanceof Error) {
        log.error({ message: error.message, payload: query });
        throw error;
      } else {
        log.error({ message: 'Postgres Query Error.', payload: query });
        throw new Error('Something went wrong Querying postgres.');
      }
    }
  }
```

**Comment by camfeghali** [comment]
for more info. If I `conn.end()` in the `finally`, ts-postgres does not log when running a single test. But throws `Already ending` when running my test suite.

**Comment by malthe** [comment]
I suspect this is a connectivity problem based on the fact that you're incorporating this jest-postgres system – but of course we shouldn't see this error, we should see something we can understand.

**Comment by camfeghali** [comment]
@malthe I figured it out. in the `beforeAll()` block of my tests, I was running a `await Promise.all(arr.map(x => await query(`insert`)))`, I changed it to build the whole query and do a single insert to the DB, removing parallel queries. Thanks for helping!
